config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/operators', to: 'operators#index'
  get '/operators/new', to: 'operators#new'
  get 'operators/:id/selection', to: 'operators#selection'
  get 'operators/:id', to: 'operators#show'
  post 'operators', to: 'operators#create'
  get 'operators/:id/weapon_selection', to: 'operator_weapons#weapon_selection'
  post 'operator_weapons/:id', to: 'operator_weapons#create'
  post 'operators/:id', to: 'operators#update'
  get 'operators/:id/secondary_selection', to: 'operator_weapons#secondary_selection'
  post 'operator_weapons/:id/secondary', to: 'operator_weapons#create_secondary'
  resources :users, only: [:new, :create, :edit, :update, :show]
  get 'users/:id/confirm_account_deletion', to: 'users#confirm'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/users/:id/delete', to: 'users#delete'
  get '/users/:id/account_deleted', to: 'users#destroy'
  get 'users/:id/operators', to: 'users#operators'

  get 'operators/:id/confirm_operator_deletion', to: 'operators#confirm'
  get '/operators/:id/delete', to: 'operators#delete'
  get '/operators/:id/operator_deleted', to: 'operators#destroy'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rainbow Six Siege Custom Operators</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="navbar">
    <% if current_user %>
      <!-- current_user will return true if a user is logged in -->
      <b><%= "Logged in as #{current_user.username}" %></b> | <%= link_to 'Home', operators_path %> | <%= link_to 'New Operator', operators_new_path %> | <%= link_to 'My Operators', "/users/#{current_user.id}/operators" %> | <%= link_to 'My Account', user_path(current_user) %> | <%= link_to 'Log Out', logout_path, method: :delete %>
    <% else %>
      <!-- not logged in -->
      <%= link_to 'Home', operators_path %> | <%= link_to 'Log In', login_path %> or <%= link_to 'Sign Up Here To Create Your Own Ops', new_user_path %>
    <% end %>
    </div>
    <hr>


    <% if notice %>
      <%= notice %>
	  <% end %>
	
	  <% if alert %>
      <%= alert %>
	  <% end %>

    <%= yield %>
  </body>
</html>